# 프로그래머스_레벨 2_입양 시각 구하기(1)
# 220810
# DATE_FORMAT 함수..

SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HOUR
HAVING HOUR >= 9 AND HOUR <= 19
ORDER BY HOUR ASC