# 프로그래머스_레벨 4_우유와 요거트가 담긴 장바구니
# 220810

SELECT DISTINCT A.CART_ID
FROM (SELECT * FROM CART_PRODUCTS WHERE NAME = 'MILK') A
INNER JOIN (SELECT * FROM CART_PRODUCTS WHERE NAME = 'YOGURT') B
ON A.CART_ID = B.CART_ID
ORDER BY A.CART_ID